import { Agency } from "../models/agency";

export const AGENCY_DATA: Agency[] = [
    {
        id: 1,
        fullName: 'Nguyen A',
        address: 'Ninh Kieu, Can Tho',
        email: 'nguyena@gmail.com',
        phone: '0698546321',
        note: 'xxxxx xxxx xxxxxxx xxxxx xxxx x',
        accountName: 'nguyena@gmail.com',
        password: '',
        contract: 'HĐBB2023/XMHT',
    },
    {
        id: 2,
        fullName: 'Tran Van Ti',
        address: 'Nga 7, Phung Hiep, Hau Giang',
        email: 'vanti@gmail.com',
        phone: '0685676321',
        note: '',
        accountName: 'vanti@gmail.com',
        password: '',
        contract: 'HĐBB2023/DMHT',
    },
    {
        id: 3,
        fullName: 'Ly Dong',
        address: 'Cho Moi, An Giang',
        email: 'lydong10@gmail.com',
        phone: '06985469877',
        note: '',
        accountName: 'lydong@gmail.com',
        password: '',
        contract: 'HĐBB2023/CMHT',
    },
    {
        id: 4,
        fullName: 'Nguyen Van Tan',
        address: 'Quan Phu Nhuan, HCM',
        email: 'vantan@gmail.com',
        phone: '0698226320',
        note: '',
        accountName: 'vantan@gmail.com',
        password: '',
        contract: 'HĐBB2023/TMHT',
    },
    {
        id: 5,
        fullName: 'Nguyen Hao',
        address: 'Moc Hoa, Long An',
        email: 'hao12@gmail.com',
        phone: '0998546331',
        note: '',
        accountName: 'hao@gmail.com',
        password: '',
        contract: 'HĐBB2023/BMHT',
    },
    {
        id: 6,
        fullName: 'Dai Ly Nam Ky',
        address: 'Quan Tan Binh, HCM',
        email: 'lananh@gmail.com',
        phone: '0927546691',
        note: '',
        accountName: 'namky@gmail.com',
        password: '12345678',
        contract: 'HĐBB2023/AMHT',
    },
];